spring.datasource.url=jdbc:sqlite://C:\Users\Dell\PycharmProjects\cf_0625\chatbot.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=testAga
spring.datasource.password=gaga5

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
